// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: pinger.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Pinger_Ping_FullMethodName = "/proto.Pinger/Ping"
)

// PingerClient is the client API for Pinger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PingerClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type pingerClient struct {
	cc grpc.ClientConnInterface
}

func NewPingerClient(cc grpc.ClientConnInterface) PingerClient {
	return &pingerClient{cc}
}

func (c *pingerClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Pinger_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingerServer is the server API for Pinger service.
// All implementations must embed UnimplementedPingerServer
// for forward compatibility
type PingerServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedPingerServer()
}

// UnimplementedPingerServer must be embedded to have forward compatible implementations.
type UnimplementedPingerServer struct {
}

func (UnimplementedPingerServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPingerServer) mustEmbedUnimplementedPingerServer() {}

// UnsafePingerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PingerServer will
// result in compilation errors.
type UnsafePingerServer interface {
	mustEmbedUnimplementedPingerServer()
}

func RegisterPingerServer(s grpc.ServiceRegistrar, srv PingerServer) {
	s.RegisterService(&Pinger_ServiceDesc, srv)
}

func _Pinger_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pinger_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingerServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Pinger_ServiceDesc is the grpc.ServiceDesc for Pinger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pinger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Pinger",
	HandlerType: (*PingerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Pinger_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pinger.proto",
}

const (
	ReverseConnection_Connect_FullMethodName = "/proto.ReverseConnection/Connect"
)

// ReverseConnectionClient is the client API for ReverseConnection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverseConnectionClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (ReverseConnection_ConnectClient, error)
}

type reverseConnectionClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseConnectionClient(cc grpc.ClientConnInterface) ReverseConnectionClient {
	return &reverseConnectionClient{cc}
}

func (c *reverseConnectionClient) Connect(ctx context.Context, opts ...grpc.CallOption) (ReverseConnection_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &ReverseConnection_ServiceDesc.Streams[0], ReverseConnection_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &reverseConnectionConnectClient{stream}
	return x, nil
}

type ReverseConnection_ConnectClient interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ClientStream
}

type reverseConnectionConnectClient struct {
	grpc.ClientStream
}

func (x *reverseConnectionConnectClient) Send(m *Chunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *reverseConnectionConnectClient) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReverseConnectionServer is the server API for ReverseConnection service.
// All implementations must embed UnimplementedReverseConnectionServer
// for forward compatibility
type ReverseConnectionServer interface {
	Connect(ReverseConnection_ConnectServer) error
	mustEmbedUnimplementedReverseConnectionServer()
}

// UnimplementedReverseConnectionServer must be embedded to have forward compatible implementations.
type UnimplementedReverseConnectionServer struct {
}

func (UnimplementedReverseConnectionServer) Connect(ReverseConnection_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedReverseConnectionServer) mustEmbedUnimplementedReverseConnectionServer() {}

// UnsafeReverseConnectionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverseConnectionServer will
// result in compilation errors.
type UnsafeReverseConnectionServer interface {
	mustEmbedUnimplementedReverseConnectionServer()
}

func RegisterReverseConnectionServer(s grpc.ServiceRegistrar, srv ReverseConnectionServer) {
	s.RegisterService(&ReverseConnection_ServiceDesc, srv)
}

func _ReverseConnection_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReverseConnectionServer).Connect(&reverseConnectionConnectServer{stream})
}

type ReverseConnection_ConnectServer interface {
	Send(*Chunk) error
	Recv() (*Chunk, error)
	grpc.ServerStream
}

type reverseConnectionConnectServer struct {
	grpc.ServerStream
}

func (x *reverseConnectionConnectServer) Send(m *Chunk) error {
	return x.ServerStream.SendMsg(m)
}

func (x *reverseConnectionConnectServer) Recv() (*Chunk, error) {
	m := new(Chunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ReverseConnection_ServiceDesc is the grpc.ServiceDesc for ReverseConnection service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReverseConnection_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ReverseConnection",
	HandlerType: (*ReverseConnectionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ReverseConnection_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pinger.proto",
}
